config-version = 2
after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

persistent-workspaces = [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '0',
    'q',
    'w',
    'e',
    'r',
    't',
    'a',
    's',
    'd',
    'f',
    'g',
    'z',
    'x',
    'c',
    'v',
    'b',
    'y',
    'u',
    'i',
    'o',
    'p',
    'h',
    'j',
    'k',
    'l',
    ';',
    'n',
    'm',
    '.comma',
    '.',
    '/',
]

on-mode-changed = []
[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.top =        0
    outer.bottom =     0
    outer.left =       0
    outer.right =      0



# MAIN --------------------------------------------------------------------------------------------
[mode.main.binding]
    shift-ctrl-alt-minus = 'resize smart -50'
    shift-ctrl-alt-equal = 'resize smart +50'
    shift-ctrl-alt-space = 'mode service'
    shift-alt-cmd-r = 'reload-config'

    # NAVIGATION
    shift-alt-cmd-j = 'focus left'
    shift-alt-cmd-k = 'focus down'
    shift-alt-cmd-i = 'focus up'
    shift-alt-cmd-l = 'focus right'

    shift-alt-cmd-u = 'move left'
    shift-alt-cmd-o = 'move right'
    shift-alt-cmd-h = 'move down'
    shift-alt-cmd-y = 'move up'

    shift-alt-cmd-p = 'layout floating'
    shift-alt-cmd-n = 'layout tiling tiles'
    shift-alt-cmd-m = 'layout tiling accordion'

    # WORKSPACES
    shift-ctrl-alt-1 = 'workspace 1'
    shift-ctrl-alt-2 = 'workspace 2'
    shift-ctrl-alt-3 = 'workspace 3'
    shift-ctrl-alt-4 = 'workspace 4'
    shift-ctrl-alt-5 = 'workspace 5'
    shift-ctrl-alt-6 = 'workspace 6'
    shift-ctrl-alt-7 = 'workspace 7'
    shift-ctrl-alt-8 = 'workspace 8'
    shift-ctrl-alt-9 = 'workspace 9'
    shift-ctrl-alt-0 = 'workspace 0'

    shift-ctrl-alt-q = 'workspace q'
    shift-ctrl-alt-w = 'workspace w'
    shift-ctrl-alt-e = 'workspace e'
    shift-ctrl-alt-r = 'workspace r'
    shift-ctrl-alt-t = 'workspace t'

    shift-ctrl-alt-a = 'workspace a'
    shift-ctrl-alt-s = 'workspace s'
    shift-ctrl-alt-d = 'workspace d'
    shift-ctrl-alt-f = 'workspace f'
    shift-ctrl-alt-g = 'workspace g'

    shift-ctrl-alt-z = 'workspace z'
    shift-ctrl-alt-x = 'workspace x'
    shift-ctrl-alt-c = 'workspace c'
    shift-ctrl-alt-v = 'workspace v'
    shift-ctrl-alt-b = 'workspace b'

    shift-ctrl-alt-y = 'workspace y'
    shift-ctrl-alt-u = 'workspace u'
    shift-ctrl-alt-i = 'workspace i'
    shift-ctrl-alt-o = 'workspace o'
    shift-ctrl-alt-p = 'workspace p'

    shift-ctrl-alt-h = 'workspace h'
    shift-ctrl-alt-j = 'workspace j'
    shift-ctrl-alt-k = 'workspace k'
    shift-ctrl-alt-l = 'workspace l'
    shift-ctrl-alt-semicolon = 'workspace ;'

    shift-ctrl-alt-n = 'workspace n'
    shift-ctrl-alt-m = 'workspace m'
    shift-ctrl-alt-comma = 'workspace .comma'
    shift-ctrl-alt-period = 'workspace .'
    shift-ctrl-alt-slash = 'workspace /'


# SERVICE -----------------------------------------------------------------------------------------
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    shift-ctrl-alt-1 = ['move-node-to-workspace 1', 'mode main']
    shift-ctrl-alt-2 = ['move-node-to-workspace 2', 'mode main']
    shift-ctrl-alt-3 = ['move-node-to-workspace 3', 'mode main']
    shift-ctrl-alt-4 = ['move-node-to-workspace 4', 'mode main']
    shift-ctrl-alt-5 = ['move-node-to-workspace 5', 'mode main']
    shift-ctrl-alt-6 = ['move-node-to-workspace 6', 'mode main']
    shift-ctrl-alt-7 = ['move-node-to-workspace 7', 'mode main']
    shift-ctrl-alt-8 = ['move-node-to-workspace 8', 'mode main']
    shift-ctrl-alt-9 = ['move-node-to-workspace 9', 'mode main']
    shift-ctrl-alt-0 = ['move-node-to-workspace 0', 'mode main']

    shift-ctrl-alt-q = ['move-node-to-workspace q', 'mode main']
    shift-ctrl-alt-w = ['move-node-to-workspace w', 'mode main']
    shift-ctrl-alt-e = ['move-node-to-workspace e', 'mode main']
    shift-ctrl-alt-r = ['move-node-to-workspace r', 'mode main']
    shift-ctrl-alt-t = ['move-node-to-workspace t', 'mode main']

    shift-ctrl-alt-a = ['move-node-to-workspace a', 'mode main']
    shift-ctrl-alt-s = ['move-node-to-workspace s', 'mode main']
    shift-ctrl-alt-d = ['move-node-to-workspace d', 'mode main']
    shift-ctrl-alt-f = ['move-node-to-workspace f', 'mode main']
    shift-ctrl-alt-g = ['move-node-to-workspace g', 'mode main']

    shift-ctrl-alt-z = ['move-node-to-workspace z', 'mode main']
    shift-ctrl-alt-x = ['move-node-to-workspace x', 'mode main']
    shift-ctrl-alt-c = ['move-node-to-workspace c', 'mode main']
    shift-ctrl-alt-v = ['move-node-to-workspace v', 'mode main']
    shift-ctrl-alt-b = ['move-node-to-workspace b', 'mode main']

    shift-ctrl-alt-y = ['move-node-to-workspace y', 'mode main']
    shift-ctrl-alt-u = ['move-node-to-workspace u', 'mode main']
    shift-ctrl-alt-i = ['move-node-to-workspace i', 'mode main']
    shift-ctrl-alt-o = ['move-node-to-workspace o', 'mode main']
    shift-ctrl-alt-p = ['move-node-to-workspace p', 'mode main']

    shift-ctrl-alt-h = ['move-node-to-workspace h', 'mode main']
    shift-ctrl-alt-j = ['move-node-to-workspace j', 'mode main']
    shift-ctrl-alt-k = ['move-node-to-workspace k', 'mode main']
    shift-ctrl-alt-l = ['move-node-to-workspace l', 'mode main']
    shift-ctrl-alt-semicolon = ['move-node-to-workspace ;', 'mode main']

    shift-ctrl-alt-n = ['move-node-to-workspace n', 'mode main']
    shift-ctrl-alt-m = ['move-node-to-workspace m', 'mode main']
    shift-ctrl-alt-comma = ['move-node-to-workspace .comma', 'mode main']
    shift-ctrl-alt-period = ['move-node-to-workspace .', 'mode main']
    shift-ctrl-alt-slash = ['move-node-to-workspace /', 'mode main']